#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        if [ -d /run/systemd/system ]; then
            systemctl stop greenhouse-datastore.service || true
        fi
        ;;
esac

exit 0